### ISSUE TITLE
atleast one new origin every 10 levels

### ISSUE THREAD

**Issue by idlefather** [SattesKrokodil/Fabric-Adventure-Pack#12]
as the tittle says.

i feel one of the main draws of the pack is the point of progreshion, an idea i had to add to this would be unlocking origins as you level up. just one or two every 10 lvl's would help support a player base as it feels exciting again when you can change to somthing new.

we already have it quite easy to reset our origin so why not take advantage of not penalising the player and give a good reason to keep playing to try out other origins.

i understand linking 3 mods like this is not easy but as you seem to be a coder i think your the best person for the job

the way i would do it is have a quest for "reach level 10..20...30 etc" and talk about what you just unlocked as well as (perhaps) a free origin reset

adding to this i feel within the game its not easy to see we even have quests so perhaps making it more visable say a popup once at lvl 5 just so people know its there. and for the server perhaps a redone spawn with text and images in item frams so show some of the thing you can do in the game. if you like i could look into making one for you and you just world edit it in.

balance could be an issue but as this is pve(mostly) i dont see the issue of some of the more powerfull origins. personaly i would balance them arround the zone you unlock at that milestone say somthing from the nether etc when your high enouth to enter.

as a side note, loving the pack so far and you even have a server to play it on! awsome.

p.s. IGN is IdleFather if you wanted to chat or drop a message on discord some time

**Comment by SattesKrokodil** [comment]
Hey there! Thanks a lot for the feedback. 

For origins the plan is (this won't be done tomorrow, takes time)

+ 10 base origins 
+ level unlocks (is possible now, was not possible before)
+ at leas one short questline for each origin to either negate a negative effect or maybe add something new to it. I am not sure about this or what the best way of implementing it would be. But I really enjoy the Vox transformations so maybe all origins will get some sort of transformation. Example for unlocks could be different new animals for Vox, ability to randomtp for enderling and so on.
+ I learned a lot about origins and how to make them in the last few weeks for the Anima modpack, I hope/think this will translate into the AP origins remake (=

Also the Quest mod is right now more or less in "testing" since we have no idea if it will cause any issues, I wanted to keep the quests simple and just import the starter page. (example what can go wrong: with the HQM quests we once experienced the funny case of infinite rewards which needed a huge roleback :/  )There will be a quest book in your inventory when you start a new world/join a server in the future that is easy to add.

**Comment by idlefather** [comment]
thank you for the reply

i assume the idea of bigger updates rather than smaller is to reduce the amount of testing needed and how many updates needed for the player base, im just inpatient lol.

what i was proposing was still a smaller starter set of origins but 2 more per level so if we say 5 starters and 2 per level then thats 15 total, if you then add on being able to change/evolve/mutate each one you have 30+ origins

so say we have world based origins
5 over world
2 stary sky
2 nether
2bublezone
2 end
2 world blender

thats a whole lot of choise and then to add a diferent mutation that adds to or takes somthing away is almost too much lol. but if you are deadset on lots then i would go with an example of say

**salmon**

brake blocks underwater as if on land
does not sink under water
can only eat plants

able to change into a fish for these effects:
breathe underwater
see underwater
faster under water
cant breath on land(half normal bubbles)

mutates into
pufferfish

brake blocks underwater as if on land
does not sink under water
can only eat plants
cats are scared of you

able to change into fish for these effects
breathe underwater
see underwater
potions have 150% duration/effect
chance to give poison when attacked
onland get the nausea effect
cant breath on land(half normal bubbles)

as you can see thats a lot and i just said 1 with 1 mutation.
if you want any more ideas i can think of more
