### ISSUE TITLE
There are conflicting IDs in the kubejs datapack for Age of Exile

### ISSUE THREAD

**Issue by brenodantas10** [SattesKrokodil/Fabric-Adventure-Pack#17]
**Describe the bug**
No problem playing but there are conflicting ids in the game and files with worng name in mmorpg/compatible_items /mmorpg/base_gear_types/ folders.

Basically,
->mmorpg/compatible_items/mmorpg/armor/leather/helmet/archers_helmet.json and 
   mmorpg/base_gear_types/archers_helmet.json are with the wrong id;

->mmorpg/compatible_items/mmorpg/armor/leather/helmet/arctic_fox_armor_chestplate.json should be arctic_fox_armor_helmet.json.

**To Reproduce**
1. Execute the Adventure Pack instance in any launcher
2. Watch the console until a STDERR appears
3. the game is trying to add an item that is already added (ghostly_armor_helmet)

**Expected behavior**
No STDERR or fewer should be showed in the console.

**Comment by panbanann** [comment]
I fixed the first one already and thanks for reporting the second one I didn't catch it before. It is as you said harmless and will probably be fixed with the update after the new Age of Exile release. We will have to redo the whole compatibility so, maybe you could then help with finding some more bits like this :)
